services:
  db:
    hostname: db
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - MSSQL_SA_PASSWORD=MyPass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    networks:
      - smarthome_db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    depends_on:
      - db
    volumes:
      - ./DeviceValidators/:/DeviceValidators/
      - ./ImportStrategies/:/ImportStrategies/
    networks:
      - smarthome
      - smarthome_db
  caddy:
    container_name: caddy
    image: caddy
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./smarthome.FrontEnd/Smarthome/dist/smarthome/browser/:/usr/share/caddy/
    depends_on:
      - backend
    networks:
      - smarthome

networks:
  smarthome:
    driver: bridge
  smarthome_db:
    driver: bridge
